# Generated by Django 4.2.2 on 2023-06-28 00:16

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='campaign_setting',
            field=models.CharField(blank=True, max_length=80, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
    ]
