# Generated by Django 4.2.2 on 2023-07-13 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_odyssey_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='adventure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_set', to='server.adventure'),
        ),
    ]
