# Generated by Django 4.2.2 on 2023-07-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_scene_adventure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='scene_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_set', to='server.scene'),
        ),
    ]
