# Generated by Django 4.2.4 on 2023-09-19 21:22

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_adventure_campaign_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='campaign_setting',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='climax',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='denoument',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='exposition',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='incitement',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='stats',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='scene',
            name='challenge',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='scene',
            name='clue',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='scene',
            name='plot_twist',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
        migrations.AlterField(
            model_name='scene',
            name='setting',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(drop database)|(drop table (adventure|custom_field|encounter|scene|user))', flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='That text is not allowed. Please revise your entry.')]),
        ),
    ]
