# Generated by Django 4.2.4 on 2023-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_adventure_campaign_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='climax_progress',
            field=models.FloatField(default=0),
        ),
    ]
